### ISSUE TITLE
Add toggle support for plugins

### ISSUE THREAD

**Issue by stefanos82** [rxi/lite-plugins#37]
I like how `drawwhitespace.lua` works, but I would like to enable it via toggle option when I need to.

I'm sure many more plugins need this feature.

Is it something it could be added easily?

**Comment by rxi** [comment]
It is not, once a plugin is loaded it can't be unloaded for the rest of the session. This is an intentional decision made for the purpose of keeping plugins simple to write -- they can hook into whatever they want and don't need to worry about cleaning up after themselves.

One thing that can be done for plugins where you want to toggle functionality is to implement it directly into the plugin, see the `hidestatus` plugin, for example. I'm unsure the `drawwhitespace` plugin would benefit from this, though, for what reason are you frequently toggling it on and off?

**Comment by stefanos82** [comment]
You misunderstood me @rxi.

Indeed what I want is exactly what `hidestatus.lua` does or should I say implements.

I'm new to Lua and I will need some time to experiment until I feel confident enough to start working on new features or bug fixes.

I'm basically trying to bring Lite to a level closer to Vim and VSCode combined.

I'm sure others would want to achieve the same as well.

**Comment by Tmpod** [comment]
> I'm basically trying to bring Lite to a level closer to Vim and VSCode combined.

And ST :P  I believe lite can become a very nice open source competitor to Sublime.   
Togglablepplugins would be a great step towards that.
