### ISSUE TITLE
Gitstatus plugin pops up cmd continually

### ISSUE THREAD

**Issue by mundusnine** [rxi/lite-plugins#41]
When using a lite.exe shortcut to open lite in the project directory, the git status plugin doesn't stop starting and stopping cmd.exe. It is probably trying to connect to git or start a git instance and it cant because its a shortcut ?

Issue doesn't happen when starting lite by clicking the exe directly. 

![image](https://user-images.githubusercontent.com/29337013/82675964-9b2dc080-9c13-11ea-92bf-21a4d9ea3afc.png)

**Comment by rxi** [comment]
This will be fixed in v1.05 -- I've updated `gitstatus` so that this shouldn't happen but the changes also mean the plugin won't work correctly on the v1.04 release. When the next version of lite is released I'll push the changes to the plugins but until then I want to keep the plugins synchronised with the current release version of lite.

**Comment by rxi** [comment]
This should be fixed with 5dd2f7cda584d43b40af0db69e41312f98c71611
